### ISSUE TITLE
as a user , I want to be able to edit an email as a new one

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/esn-frontend-inbox#202]
#### CURRENT

Not possibble

#### EXPECTED 

Like in OBM and Thunderbird :

![Capture d’écran de 2020-10-09 11-58-26](https://user-images.githubusercontent.com/11298249/95570330-0e02d100-0a27-11eb-9073-219e15776b1c.png)

![Capture d’écran de 2021-02-17 10-04-15.png](https://images.zenhubusercontent.com/5f9c1883317e52f28f3396ce/fe72062b-03d2-4d1c-a415-99f4d8501b8d)

#### SPEC : 

- `edit as a new` create an email as a new one with the **subject, the body and recipents (to, cc, cci).**

**Comment by fabienmoyon** [comment]
#### EXPECTED 

![Capture d’écran de 2021-02-17 10-04-15.png](https://images.zenhubusercontent.com/5f9c1883317e52f28f3396ce/fe72062b-03d2-4d1c-a415-99f4d8501b8d)


#### SPEC : 

- `edit as a new` create an email as a new one with the subject, the body and recipents (to, cc, cci).

**Comment by fabienmoyon** [comment]
Edit as an new one must include attachments is need it @oubchid  

https://images.zenhubusercontent.com/276892191/de2c98cf-9741-4944-b7d9-7ee6420fad60/inbox___openpaas__3_.mp4

**Comment by tlle14** [comment]
Hi @fabienmoyon 
Retest failed!

1. The email body becomes quoted like in the forwarded email
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/51ba2f6b-72fc-4984-b8e2-017ba0dc351b)

2. I cannot test the email has Linshare attachments on DEV platform. 

3. Others: 
- Keep the recipients (To/CC/Bcc): pass
- Keep  the subject: pass
- Keep the email body (format/content/inline image): failed 
- Keep the attachments: pass
- Keep the Linshare attachment: cannot test
- Keep the Read receipt: No

**Comment by fabienmoyon** [comment]
Hello @tlle14,

@oubchid will fix that :+1:

**Comment by fabienmoyon** [comment]
Hello @tlle14,

Can you please test if it's good now.
