### ISSUE TITLE
User Feedback > Composer is stop working on Firefox when user drags and drops a paragraph into an unintended place

### ISSUE THREAD

**Issue by tlle14** [linagora/esn-frontend-inbox#204]
# Actual Result

Drag and drop a text into the address bar on the composer, it makes the composer stop working.
The user may lose his composed email.

![screenshot_35](https://user-images.githubusercontent.com/69950655/95671839-71c30080-0bc5-11eb-9970-69fcebc6824c.png)

![Peek 2020-10-11 13-34](https://user-images.githubusercontent.com/69950655/95671954-d2067200-0bc6-11eb-9d71-42f741520510.gif)

# Steps
1. Open the composer
2. Drag the text and hover on the composer but not drop into the email body
3. Leave the text outside the composer. The label "drop the file" on the composer doesn't disaappear
4. Drag and drop another text into the body of the composer.

# Expected Result
Please fix the exception log

# Environment
Ubuntu Firefox

**Comment by alagane** [comment]
Might be related to https://github.com/summernote/summernote/issues/3981

**Comment by tlle14** [comment]
Cannot reproduce anymore
