### ISSUE TITLE
Unified Inbox name should be removed from Email module

### ISSUE THREAD

**Issue by tlle14** [linagora/esn-frontend-inbox#280]
# Precondition
As per https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/159
# Actual Result
Navigate from other modules to Email module, it displays "Unified Inbox" screen
![image](https://user-images.githubusercontent.com/69950655/100694898-9caa2380-33c2-11eb-9b22-9b54d7bcb85f.png)
**=> Expected: It should display "All mail" screen as a default**

Create a folder, it still lists Unified Inbox as a parent folder
![image](https://user-images.githubusercontent.com/69950655/100696201-99646700-33c5-11eb-91fc-897d9e87166e.png)
**=> Expected: It should rename the "Unified Inbox" to null or `None` or something else**

# Environment
DEV platform

**Comment by fabienmoyon** [comment]
@chibenwa and me discussed about the issue firectly in the PR : https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/309#issuecomment-748938250

**Comment by chibenwa** [comment]
`All mails` had not been identified as critical to optimize performance wise.

It requires ElasticSearch, an extra middleware to be rendered server side. This harms plateform resiliency. Extra backend work is required to have similar experience than single mailbox display.

Also, as a user, I care about newly arrived emails, akka INBOX. While having this `All mail` view is usefull (ie I moved an email but do not remember in which mailbox I did put it) I really wonder if - and why - this should be the default behaviour.

From my side, **this is a clear no**.

My takeaways are:

 - The default page should be where the emails arrived, without noise. Today this is called `Inbox`
 - All mail aggregation is expensive and should not be the default.
 -  Email folder classification is useful, is something the user defines filters for, and spend time to do manually, we should not bypass it by default.

**Comment by tlle14** [comment]
@fabienmoyon @oubchid @MichaelBailly @rouazana please continue working on this ticket

**Comment by oubchid** [comment]
@tlle14 on it ;)

**Comment by fabienmoyon** [comment]
Now `/` no more redirect to `/unifiedinbox/inbox`. 

Need to be fix

**Comment by alagane** [comment]
Redirections are not related to this issue. Closing.
