### ISSUE TITLE
As an User I want to be able to insert a link in the composer

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/esn-frontend-inbox#427]
![Capture d’écran de 2021-04-22 17-25-39](https://user-images.githubusercontent.com/11298249/115741181-cd015700-a38f-11eb-9092-a7e7f1132050.png)

in `modules/linagora.esn.unifiedinbox/frontend/app/constants.js` add `['link', ['link']]` in `INBOX_SUMMERNOTE_OPTIONS` constant : 

```
.constant('INBOX_SUMMERNOTE_OPTIONS', {
    focus: false,
    airMode: false,
    disableResizeEditor: true,
    toolbar: [
      ['style', ['style']],
      ['color', ['color']],
      ['font', ['bold', 'italic', 'underline', 'strikethrough']],
      ['alignment', ['paragraph', 'ul', 'ol']],
	  ['link', ['link']]
    ],
    keyMap: {
      pc: {'CTRL+ENTER': '', ENTER: 'insertParagraph'},
      mac: {'CMD+ENTER': '', ENTER: 'insertParagraph'}
    }
  })
```

**Comment by chibenwa** [comment]
I think "open in new window" should be true by default, and I wonder if it should not always be true in the context of an email. Why asking the user about it?

**Comment by fabienmoyon** [comment]
> I think "open in new window" should be true by default, and I wonder if it should not always be true in the context of an email. Why asking the user about it?

Yes true, I will configure it by default

**Comment by fabienmoyon** [comment]
It's possible from the version `v0.8.4` see https://github.com/summernote/summernote/pull/2195

We are currently using the fork version `v0.8.2-1` released on 21 Sep 2016 https://github.com/linagora/summernote/releases/tag/0.8.2-1 and https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/blob/main/package.json#L72
`
I propose to create a task to upgrade summernote to the latest version `v0.8.18` released on 20 May 2020 https://github.com/summernote/summernote/releases and to check how the version behaves in the composer (I hope this version will fix many issues met by users).

We have some others dependencies to update like https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/431 and https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/security/dependabot

**Comment by chibenwa** [comment]
+1 for summernote version update.

**Comment by Arsnael** [comment]
+1 as well, if it can solve this easily without much work
