### ISSUE TITLE
as a user I want to be connected every time

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/esn-frontend-inbox#453]
#### Currently

After a long  time (offline) `jmap` API return a 401 Unauthorized so we need to refresh the page to get again jmap response.

![Capture d’écran de 2021-05-18 08-38-35](https://user-images.githubusercontent.com/11298249/118695475-8a576100-b80d-11eb-87ce-ccff1814d146.png)

#### Expected

When `jmap` API return a 401 Unauthorized we need to get a new token and to call again the jmap request

**Comment by tanandy** [comment]
we should be disconnected from openpaas after a long time. for security reasons, so we need to be redirected to login page.

btw, if op session is still valid and jwt token isnt . we need to align session and token lifetime

**Comment by chibenwa** [comment]
Duplicates https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/415

**Comment by oubchid** [comment]
> After a long time (offline) jmap API return a 401 Unauthorized so we need to refresh the page to get again jmap response.

@fabienmoyon long time, you mean 1 day, 2 hours ? Do you know the TTL of the jwt token

**Comment by oubchid** [comment]
> > After a long time (offline) jmap API return a 401 Unauthorized so we need to refresh the page to get again jmap response.
> 
> @fabienmoyon long time, you mean 1 day, 2 hours ? Do you know the TTL of the jwt token

By default, token JWT lifetime is 12h, and no idea yet about op session relationship 

![image](https://user-images.githubusercontent.com/7097550/122030530-25703600-cdce-11eb-8bcf-9a21c024ce1e.png)

**Comment by chibenwa** [comment]
> By default, token JWT lifetime is 12h, and no idea yet about op session relationship

Make it 3h.

And, please, handle these nasty 301 and regenerate this token!

**Comment by oubchid** [comment]
> Please, all you need to do is to handle these nasty 401 and regenerate this token!

But please avoid this kind of answer 

We are discussing here to identify what's done actualy and why !

**Comment by oubchid** [comment]
> Please, all you need to do is to handle these nasty 401 and regenerate this token!

But please avoid this kind of remark 

We are discussing here to identify what's done actually and why ! 

We don't have a lot of documentation we do our best, so discussions / remarks important are welcome

**Comment by chibenwa** [comment]
Yes, proper error handling is need. 

As this issue have had been standing for 2 months without being addressed, here are some design suggestions.

Let me suggest to catch the exception caused by the 401, regenerate the token, then replay the request?

Shouldn't we have that done as part of the JMAP library? Most HTTP libraries support such schemes, it should not be hard to set up.

**Comment by tanandy** [comment]
sure, http interceptors is a good stuff to handle that. do we have already some in OpenPaas @chamerling ? @tuanlc

**Comment by tuanlc** [comment]
@tanandy As far as I remember, HTTP interceptor has been used in OpenPaaS but I don't know exactly where/when :thinking: 

BTW, add an interceptor to catch 401 response and use ESN authenticated session to generate a new JWT token to the JMAP server is a good idea and it is possible.

Another way that has been using by the calendar module (AFAIK) is from the JWT token, clients can parse and get the expiring time. Then cliens can know when to re-generate the new JTW token (for example, 10 seconds before expiring). @renaudboyer may have more info on this.

**Comment by chibenwa** [comment]
> clients can parse and get the expiring time

Likely brittle as it requires clock syncronisation. Go out of sync with q clock skew and you will get issues with this design.

**Comment by tanandy** [comment]
thank you, if someone can open the car and check behind the cap. 
Lets reuse HTTP interceptor to make it works, example above is a good start.

**Comment by simonelbaz** [comment]
Maybe thé refresh_token could be used to refresh the access_token in case it has expired

**Comment by tanandy** [comment]
> Maybe thé refresh_token could be used to refresh the access_token in case it has expired

Sûre. Btw using refresh token for spa without rotating mecanism is a security issue.

Btw here it is mainly the jwt token that expires before. We need to Sync jwt and Access token

**Comment by simonelbaz** [comment]
the link (https://wstutorial.com/am/obtain-jwt-from-keycloak.html) shows that the access_token + refresh_token are packed into the JWT token.

**Comment by tanandy** [comment]
> the link (https://wstutorial.com/am/obtain-jwt-from-keycloak.html) shows that the access_token + refresh_token are packed into the JWT token.

yes we are aware of what keycloak provides, but here its not the topic. one more time, we shouldnt use refresh token for SPA without rotating mechanism
