### ISSUE TITLE
API Problem for identities

### ISSUE THREAD

**Issue by alagane** [linagora/esn-frontend-inbox#465]
How to reproduce initial problem?
Start openpaas-platform-docker-dev with esn, inbox, james, account.
Configure it.
Login into inbox and try to write a new mail.
The request to get identities will not fulfill because the OPTIONS is not "authorized" on esn backend
```
http://backend.open-paas.org.local/unifiedinbox/api/inbox/users/60b4fd5367fa6600b9af1d9f/identities
```
See https://ci.linagora.com/linagora/lgs/openpaas/esn/blob/master/backend/webserver/routes.js#L8 where only /api is authorized.
Adding this line solves the problem
```js
application.all('/unifiedinbox/api/*', cors({origin: true, credentials: true}));
```
The file serving the identities seems to be this one: https://github.com/linagora/linagora.esn.unifiedinbox/blob/master/backend/webserver/api/users/index.js
So there are also some other services on the same project served on `/unifiedinbox/api/` but it this a good design choice?
We could change the API to serve on /api, but we would first:
[ ] list this API services routes
[ ] need to check if there are no collisions with other services

**Comment by tanandy** [comment]
interesting, we need the review the cors settings for the api. 

please make it configurable, '*' is not possible for production we need to set specific path

**Comment by alagane** [comment]
For cors parameters, I just took the same than `/api/*` defined in https://ci.linagora.com/linagora/lgs/openpaas/esn/blob/master/backend/webserver/routes.js#L8
This PR should solve the problem: https://github.com/linagora/linagora.esn.unifiedinbox/pull/4
