### ISSUE TITLE
Fix mailboxes badge with `jmap-client`

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/esn-frontend-inbox#472]
#### current

On the feature-jmap1 branch, during the migration from `jmap-draft-client` to `jmap-client` we lost  mailboxes badge

![Capture d’écran de 2021-06-10 20-47-53](https://user-images.githubusercontent.com/11298249/121582958-f5bcd900-ca2f-11eb-85b7-5c4b8f53cb1b.png)

`Mailboxes/get` response : 

```
id: "ae48df30-18e9-11eb-a677-2990b970028d"
isSubscribed: true
myRights: {mayReadItems: true, mayAddItems: true, mayRemoveItems: true, maySetSeen: true, maySetKeywords: true,…}
name: "INBOX"
namespace: "Personal"
quotas: {#private&userd@qa.open-paas.org: {Storage: {used: 709431673}, Message: {used: 23870}}}
#private&userd@qa.open-paas.org: {Storage: {used: 709431673}, Message: {used: 23870}}
rights: {}
role: "inbox"
sortOrder: 10
totalEmails: 1209
totalThreads: 1209
unreadEmails: 713
unreadThreads: 713
```

#### expected 

Like with jmapdraft-client with `getMailboxes` response : 

```
id: "208f8410-ef2b-11ea-8665-3109e4489b2e"
mayAddItems: true
mayCreateChild: true
mayDelete: true
mayReadItems: true
mayRemoveItems: true
mayRename: true
mustBeOnlyMailbox: false
name: "Drafts"
namespace: {type: "Personal"}
parentId: null
quotas: {,…}
role: "drafts"
sharedWith: {}
sortOrder: 30
totalMessages: 40
totalThreads: 0
unreadMessages: 6
unreadThreads: 0
```

![Capture d’écran de 2021-05-19 13-42-01](https://user-images.githubusercontent.com/11298249/121583043-11c07a80-ca30-11eb-99e2-982017e69603.png)

**Comment by alagane** [comment]
Removed from Polish sprint: not related

**Comment by alagane** [comment]
I made a duplicate by mistake: https://github.com/linagora/esn-frontend-inbox/issues/547
It is fixed by https://github.com/linagora/esn-frontend-inbox/pull/548
