### ISSUE TITLE
handle  the tokenAPI promise rejection when initializing the jmap client

### ISSUE THREAD

**Issue by rezk2ll** [linagora/esn-frontend-inbox#482]
![image](https://user-images.githubusercontent.com/6764881/122788506-4cd37100-d2ae-11eb-8685-dfba3529adaa.png)

# clues:

- do not destructure the `tokenAPI.getWebToken()` ie code becomes like:
```js
]).then(function([tokenApiResponse, apiUrl, downloadUrl]) {
...
check if the response is defined and call the `withAuthenticationToken` if yes
```
- add some catch

**Comment by alagane** [comment]
What should be done?
The JMAP client should not be initialized at all?
A new token should be fetched?
An error should be shown saying JMAP need authentication to make requests?

**Comment by rezk2ll** [comment]
what happens is related to the https://github.com/linagora/customers/issues/55, the first request to jwt/generate fails and jmap client doesn't have a jwt so it wouldn't make any sense to initialize it.

we need to handle the promise rejection in code, cause it will always assume we have a token and tries to access some undefined data.

**Comment by oubchid** [comment]
@rezk2ll as you said this fix is not needed anymore ?

https://github.com/linagora/esn-frontend-inbox/pull/492#issuecomment-871495095
