### ISSUE TITLE
on Firefox, drag and drop text in the compose should not crash the composer

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/esn-frontend-inbox#515]
#### Expected 

like chrome not impact and crash the composer!

Chrome 

https://user-images.githubusercontent.com/11298249/137274854-81080b08-8671-459f-8803-41f68438e2dc.mp4

Firebox 

https://user-images.githubusercontent.com/11298249/137274876-7d8c018c-330e-440a-af32-7a05e71b9fde.mp4

**Comment by alagane** [comment]
Upgrading summernote from 0.8.2-1 to 0.8.18 seems to solve the problem.
Version cannot be set to latest (0.8.20) because of some bug fixed but not yet released: https://github.com/summernote/summernote/issues/4164
