### ISSUE TITLE
Prompted to leave page when opening attachment

### ISSUE THREAD

**Issue by alagane** [linagora/esn-frontend-inbox#556]
**Given** I am reading a mail with attachments and I have a composer openened (also minimize) with new content written in it.
**When** I click on an attachment
**What happens** I am prompted asking if I want to leave the page with unsaved data
**What should happen** I should not be prompted because I am not leaving the page

The solution is to add a `download` attribute on the anchor tag, to tell the browser I am downloading a file and not leaving the page. (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)
The file to modify is `attachment-download-action.pug`.

**Comment by fabienmoyon** [comment]
introduce in https://github.com/linagora/esn-frontend-inbox/issues/433

**Comment by alagane** [comment]
The pull request does not fix the bug.
